"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../component/sidebar";
import { useState, useEffect } from "react";
import { auth } from "../firebase/config";
import { onAuthStateChanged, User, signOut } from "firebase/auth";
import { useRouter } from "next/navigation";
import Shortener from "../component/shorten";
import { FaRegUserCircle } from "react-icons/fa";
import { FaPlus } from "react-icons/fa6";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState<User | null>(null);
  const router = useRouter();
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        setUser(user);
        setLoading(false);
      } else {
        router.push("/");
      }
    });

    return () => {
      unsubscribe();
    };
  }, [router]);
  // if (loading) {
  //   return (
  //     <div className="grid place-content-center h-screen">
  //       <p >
  //       <svg
  //           className="motion-reduce:hidden bg-slate-300 animate-spin ..."
  //           viewBox="0 0 24 24"
  //         ></svg>
  //         Processing
  //       </p>
  //     </div>
  //   );
  // }
  return (
      <div className={inter.className}>
        <div className="flex h-screen overflow-hidden">
          <div className="h-screen">
            <Sidebar />
          </div>
          <div className="flex-1 overflow-y-auto">
            <main className="sticky bg-white top-0 z-50  flex justify-between items-center py-3 px-6 border-solid border-2 border-slate-200">
              <nav>
                <h1 className=" font-bold text-base">Dashboard</h1>
              </nav>
              <div className="flex items-center gap-4">
                <div>
                <Shortener />
                </div>
                <div className="flex gap-1">
                  <FaRegUserCircle className="text-2xl text-slate-300 cursor-pointer" />
                  <h1 className="text-slate-400">{user?.email}</h1>
                  <h1 className="text-slate-400">{user?.displayName}</h1>
                </div>
              </div>
            </main>
            <div className="z-0 ">
            {children}
            </div>
          </div>
        </div>
      </div>
  );
}
